In [1]:
import pandas as pd

In [2]:
s1 = pd.read_csv("n_gram_mask_bert_v1_weight_v2/submit_0.96034970703125.csv",header=None)

In [3]:
s2 = pd.read_csv("new_bert_weight_v2/submit_0.960414453125.csv",header=None)

In [4]:
s1.head()

    0                                                  1
0  0|  |0.015310692321509122 0.00848104446195066 0.01...
1  1|  |0.001988692837767303 0.002535762172192335 0.0...
2  2|  |0.005384361511096359 0.006568876933306456 0.0...
3  3|  |0.01146786892786622 0.0061513845343142744 0.0...
4  4|  |0.00786744561046362 0.01184350810945034 0.006...

In [5]:
s1[1]=s1[1].apply(lambda x:x[1:].split())
s1.head()

    0                                                  1
0  0|  [0.015310692321509122, 0.00848104446195066, 0....
1  1|  [0.001988692837767303, 0.002535762172192335, 0...
2  2|  [0.005384361511096359, 0.006568876933306456, 0...
3  3|  [0.01146786892786622, 0.0061513845343142744, 0...
4  4|  [0.00786744561046362, 0.01184350810945034, 0.0...

In [6]:
s2[1]=s2[1].apply(lambda x:x[1:].split())
s2.head()

    0                                                  1
0  0|  [0.006712959334254265, 0.002904167165979743, 0...
1  1|  [0.0026349883526563646, 0.003142697876319289, ...
2  2|  [0.011335882917046547, 0.008515555597841739, 0...
3  3|  [0.008149998635053635, 0.003202264243736863, 0...
4  4|  [0.009360553976148368, 0.019227813370525836, 0...

In [7]:
import numpy as np

def blend(s1,s2):
    s1 = [float(i) for i in s1]
    s2 = [float(i) for i in s2]
    m = (np.array(s1)+np.array(s2))/2
    return m

s = s1.copy()

In [8]:
s[2] = s2[1]

In [9]:
s.head()

,0,1,2
0,0|,"[0.015310692321509122, 0.00848104446195066, 0....","[0.006712959334254265, 0.002904167165979743, 0..."
1,1|,"[0.001988692837767303, 0.002535762172192335, 0...","[0.0026349883526563646, 0.003142697876319289, ..."
2,2|,"[0.005384361511096359, 0.006568876933306456, 0...","[0.011335882917046547, 0.008515555597841739, 0..."
3,3|,"[0.01146786892786622, 0.0061513845343142744, 0...","[0.008149998635053635, 0.003202264243736863, 0..."
4,4|,"[0.00786744561046362, 0.01184350810945034, 0.0...","[0.009360553976148368, 0.019227813370525836, 0..."

In [10]:
s['result'] =  s.apply(lambda x:blend(x[1],x[2]),axis=1)

In [11]:
s.head()

,0,1,2,result
0,0|,"[0.015310692321509122, 0.00848104446195066, 0....","[0.006712959334254265, 0.002904167165979743, 0...","[0.011011825827881693, 0.0056926058139652016, ..."
1,1|,"[0.001988692837767303, 0.002535762172192335, 0...","[0.0026349883526563646, 0.003142697876319289, ...","[0.0023118405952118337, 0.002839230024255812, ..."
2,2|,"[0.005384361511096359, 0.006568876933306456, 0...","[0.011335882917046547, 0.008515555597841739, 0...","[0.008360122214071453, 0.0075422162655740975, ..."
3,3|,"[0.01146786892786622, 0.0061513845343142744, 0...","[0.008149998635053635, 0.003202264243736863, 0...","[0.009808933781459927, 0.004676824389025568, 0..."
4,4|,"[0.00786744561046362, 0.01184350810945034, 0.0...","[0.009360553976148368, 0.019227813370525836, 0...","[0.008613999793305994, 0.015535660739988088, 0..."

In [12]:
s['submit'] =s['result'].apply(lambda x:[str(i) for i in x])

In [13]:
s['submit'] = s['submit'].apply(lambda x:" ".join(x))

In [14]:
s.head()

,0,1,2,result,submit
0,0|,"[0.015310692321509122, 0.00848104446195066, 0....","[0.006712959334254265, 0.002904167165979743, 0...","[0.011011825827881693, 0.0056926058139652016, ...",0.011011825827881693 0.0056926058139652016 0.0...
1,1|,"[0.001988692837767303, 0.002535762172192335, 0...","[0.0026349883526563646, 0.003142697876319289, ...","[0.0023118405952118337, 0.002839230024255812, ...",0.0023118405952118337 0.002839230024255812 0.0...
2,2|,"[0.005384361511096359, 0.006568876933306456, 0...","[0.011335882917046547, 0.008515555597841739, 0...","[0.008360122214071453, 0.0075422162655740975, ...",0.008360122214071453 0.0075422162655740975 0.0...
3,3|,"[0.01146786892786622, 0.0061513845343142744, 0...","[0.008149998635053635, 0.003202264243736863, 0...","[0.009808933781459927, 0.004676824389025568, 0...",0.009808933781459927 0.004676824389025568 0.02...
4,4|,"[0.00786744561046362, 0.01184350810945034, 0.0...","[0.009360553976148368, 0.019227813370525836, 0...","[0.008613999793305994, 0.015535660739988088, 0...",0.008613999793305994 0.015535660739988088 0.00...

In [15]:
s[0]=s[0].apply(lambda x:x[:-1])
s.head()

,0,1,2,result,submit
0,0,"[0.015310692321509122, 0.00848104446195066, 0....","[0.006712959334254265, 0.002904167165979743, 0...","[0.011011825827881693, 0.0056926058139652016, ...",0.011011825827881693 0.0056926058139652016 0.0...
1,1,"[0.001988692837767303, 0.002535762172192335, 0...","[0.0026349883526563646, 0.003142697876319289, ...","[0.0023118405952118337, 0.002839230024255812, ...",0.0023118405952118337 0.002839230024255812 0.0...
2,2,"[0.005384361511096359, 0.006568876933306456, 0...","[0.011335882917046547, 0.008515555597841739, 0...","[0.008360122214071453, 0.0075422162655740975, ...",0.008360122214071453 0.0075422162655740975 0.0...
3,3,"[0.01146786892786622, 0.0061513845343142744, 0...","[0.008149998635053635, 0.003202264243736863, 0...","[0.009808933781459927, 0.004676824389025568, 0...",0.009808933781459927 0.004676824389025568 0.02...
4,4,"[0.00786744561046362, 0.01184350810945034, 0.0...","[0.009360553976148368, 0.019227813370525836, 0...","[0.008613999793305994, 0.015535660739988088, 0...",0.008613999793305994 0.015535660739988088 0.00...

In [16]:
sub_id=s[0].values
pres_all = s['submit'].tolist()
str_w=''
with open(f'blend.csv','w') as f:
    for i in range(len(sub_id)):
        prob= pres_all[i]
#         pres_fold=[str(p) for p in pres_fold]
#         prob = " ".join(pres_fold)
        str_w+=sub_id[i]+'|'+','+'|'+prob+'\n'
    str_w=str_w.strip('\n')
    f.write(str_w)

In [17]:
!head -10 blend.csv

0|,|0.011011825827881693 0.0056926058139652016 0.007446388225071132 0.005523474351502955 0.004388714919332414 0.0036175018758513033 0.003945466154254973 0.44416141510009766 0.03378683188930154 0.4183565236628055 0.007803005864843726 0.004289566003717483 0.005752709635999054 0.006157495360821485 0.005458018148783595 0.00886780449654907 0.006521886843256652
1|,|0.0023118405952118337 0.002839230024255812 0.0027446583611890675 0.0023355828947387632 0.002638016093987972 0.0017709737527184187 0.001636465673800558 0.002535071561578661 0.002560998848639429 0.0023129221284762026 0.0019903827691450716 0.0020621267729438843 0.0017452610074542463 0.0018354949308559297 0.0025299555389210584 0.0034463386051356796 0.0026754694525152447
2|,|0.008360122214071453 0.0075422162655740975 0.006925605633296072 0.006500776577740908 0.8831797361373901 0.007175131840631366 0.00473851605784148 0.006128693325445056 0.007585040666162967 0.006643827306106687 0.005401507508940995 0.015215514320880174 0.004832553607411682 0.004783102707006037 0.004821149306371808 0.01295359181240201 0.012203998444601894
3|,|0.009808933781459927 0.004676824389025568 0.025002606306225063 0.0070848539238795635 0.007620628550648689 0.07663169864099473 0.06753197396174074 0.009247068292461335 0.00756939547136426 0.08231418412178755 0.009292693249881266 0.005556145263835788 0.23194708516821266 0.010893677128478885 0.08162914076820016 0.06826124887447804 0.0793605463579297
4|,|0.008613999793305994 0.015535660739988088 0.00488841583719477 0.008631117828190326 0.0095317377243191 0.006321473186835647 0.00742059457115829 0.03396476553753018 0.9409593343734741 0.33844533488154416 0.044827272184193134 0.009286184795200825 0.007828368153423072 0.009242841880768536 0.014806797076016665 0.009724860033020376 0.018683872651308775
5|,|0.6051944017410278 0.010610893601551652 0.010579724749550223 0.007861396903172136 0.01187589894980192 0.004217414534650743 0.004964723251760006 0.8530291020870209 0.005379841313697398 0.01867285938933492 0.005170762352645398 0.00848278575576842 0.005083015374839306 0.007546948688104749 0.009649640414863825 0.013491399772465228 0.0072830733843147755
6|,|0.017271528672426942 0.01749065071344376 0.018198247253894805 0.016873025055974725 0.048438582196831705 0.9480839550495148 0.018412134051322936 0.02009564023464918 0.019555308204144237 0.01861885776743293 0.019153597950935363 0.050112693756818774 0.8396973669528961 0.016536726895719764 0.021131516434252262 0.9139256715774535 0.021160945296287537
7|,|0.0035909168189391496 0.00254941217135638 0.002774744527414441 0.0022825606167316435 0.0026981468778103593 0.0016034636413678528 0.0015764844720251858 0.0041561024496331814 0.0023234681691974403 0.002354286890476942 0.0019270050805062057 0.0019711404922418295 0.0015929842251352967 0.0018932414473965765 0.0023582257563248277 0.0033437838079407815 0.0025838709669187667
8|,|0.0023269371828064326 0.002833184669725597 0.0027925103902816774 0.00229425203287974 0.0026048453990370037 0.0016041450784541667 0.0015613555791787804 0.0023854814236983655 0.0024028867250308395 0.002315554488450289 0.0020580365089699626 0.0018978088395670057 0.0015347988111898303 0.0017738800961524248 0.002373041794635355 0.0038928885711357 0.0026476561790332196
9|,|0.0025364683009684087 0.002765645505860448 0.0025285316398367284 0.0023776187445037067 0.0026046365615911785 0.0016340235131792724 0.0016091558849439026 0.002630931104067713 0.0026838726131245497 0.0023850992321968077 0.002091781748458743 0.0020397234358824788 0.0017056486452929676 0.0018533270689658821 0.002669443003833294 0.0029436170356348158 0.002671131445094943

In [18]:
! head -10 new_bert_weight_v2/submit_0.960414453125.csv

0|,|0.006712959334254265 0.002904167165979743 0.004691863059997558 0.0029251388274133205 0.003010572795756161 0.0021697906078770755 0.00240413760766387 0.1960924193263054 0.006205976195633412 0.2413489118218422 0.004139026813209057 0.002792315743863583 0.003434189804829657 0.0033559057861566543 0.0027679330203682186 0.004549527680501342 0.004001416405662895
1|,|0.0026349883526563646 0.003142697876319289 0.002839827537536621 0.0025824039708822965 0.0028088119346648456 0.0018957710824906826 0.0017789616715162993 0.002850342867895961 0.0027596353087574244 0.0024290550500154495 0.002239483827725053 0.0023546013981103897 0.0018753205658867955 0.001838029664941132 0.002651961985975504 0.003613767307251692 0.002605945896357298
2|,|0.011335882917046547 0.008515555597841739 0.008230052608996629 0.008107151743024588 0.9371308207511901 0.009369550179690123 0.005904349312186241 0.0072212984785437586 0.009184877574443816 0.008020588383078574 0.006348157301545143 0.013267787359654903 0.005871229153126478 0.005827942350879312 0.005348101165145636 0.013788384757936001 0.013511685654520988
3|,|0.008149998635053635 0.003202264243736863 0.011750170215964317 0.004751972900703549 0.004680088814347982 0.012359289592131973 0.014723447896540166 0.006907626474276185 0.009610566217452288 0.09028678610920907 0.004495309758931398 0.0042558996938169 0.03927517738193274 0.003206182178109884 0.12990598529577255 0.004370113974437118 0.09274736568331718
4|,|0.009360553976148368 0.019227813370525836 0.003477774071507156 0.010405805613845586 0.011581885255873203 0.006869996152818203 0.008285496477037668 0.04236780628561974 0.9571245551109314 0.3984236061573029 0.04339237473905087 0.011028872709721327 0.009839820303022861 0.009584134630858897 0.017985944636166096 0.009929940849542618 0.02108460497111082
5|,|0.5547289967536926 0.010482188500463962 0.00926601542159915 0.007239457126706839 0.012182284332811832 0.004231562046334148 0.004825659841299057 0.8501006841659546 0.004750108113512397 0.01747223883867264 0.004580326285213232 0.009417812153697015 0.005665299249812961 0.007515515107661486 0.009963225666433572 0.011467292346060276 0.006868849415332079
6|,|0.01708888988941908 0.016902098059654237 0.017952335998415947 0.018240425363183023 0.04604613557457924 0.9564536213874817 0.017662038654088975 0.021741826459765433 0.019601329416036605 0.020261626690626144 0.020613857731223106 0.050298766046762464 0.8898986577987671 0.016961050406098365 0.019884955510497092 0.9057438731193542 0.0207315094769001
7|,|0.0036554909776896237 0.0028338188771158458 0.0031637684907764195 0.0026050013024359942 0.002830892521888018 0.0017789016244933009 0.0018178959609940649 0.004062175657600165 0.0023904543137177824 0.0025476216338574885 0.0022139673586934806 0.0022352874977514146 0.0017951385350897908 0.002036018134094775 0.002422103565186262 0.0033867497462779284 0.002711381437256932
8|,|0.0025013369508087636 0.0032333880197256805 0.002986672753468156 0.002572075044736266 0.0026563997846096752 0.001751087699085474 0.0017089940141886474 0.0025881781708449124 0.002653209213167429 0.002503941813483834 0.0023573693353682755 0.002220353716984391 0.0017344080144539476 0.0019085452891886233 0.002557495515793562 0.00395872644148767 0.0025652717333287
9|,|0.0027598127257078887 0.003071334166452289 0.002734672650694847 0.002722257561981678 0.0028814499732106925 0.0018522193655371665 0.0018142156768590212 0.002910339692607522 0.0028843328822404147 0.0024075763765722515 0.0023265792056918143 0.0024267873726785184 0.0019558327971026302 0.001942249876447022 0.0026094384491443636 0.0030302603263407946 0.0026649929117411376